# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpost',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellpost',
            name='status',
            field=models.CharField(choices=[('d', '도서'), ('b', '부동산'), ('g', '가구'), ('j', '전자기기'), ('h', '화장품'), ('e', '의류'), ('s', '스포츠'), ('h', '생활용품'), ('g', '기타')], max_length=1),
        ),
    ]
