# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0002_auto_20170807_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellpost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sellpost',
            name='status',
        ),
    ]
