# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0003_auto_20170810_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
