# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellbuy', '0004_auto_20170811_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellpost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
